### DISCUSSION TITLE
Passing variables to stack file

### DISCUSSION THREAD

**Discussion by francisdeh** [cssnr/portainer-stack-deploy-action#11] [Q&A] [answered]
@smashedr Cheers for the impressive work.
Does the current package version support the possibility of passing variables to the stack files during the deployment?
I am thinking of something in the format:
```
- name: Deploy stack to Portainer
   uses: cssnr/portainer-stack-deploy-action@v1
   with:
      ...
      variables: ''{"TAG" : ":tag-name"}
      name: stack
      file: stack.yaml
      type: file

```
for a stack file with image of the format
```
version: "3.9"

services:
  app:
     image: registry.docker.org/app:${TAG:-latest}
```
